"""new fields in user model

Revision ID: 9557c83ff47c
Revises: 1e65f1f8c073
Create Date: 2020-12-05 22:32:42.279728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9557c83ff47c'
down_revision = '1e65f1f8c073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
